apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: KubenetesTest
  name: KubenetesTest
  namespace: 01-shopmaster
spec:
  ports:
  - name: 8082-8082
    port: 8082
    protocol: TCP
    targetPort: 8082
    nodePort: 30001
  selector:
    app: KubenetesTest
  type: ClusterIP
status:
  loadBalancer: {}
